### PR TITLE
Upgrade mongojs dependency to version 2.4.0

### PR DESCRIPTION
**Pull request by ShaneKilkelly**
- Upgrade in package.json
- Use new connection syntax
- Fix unit tests, issues with object equality

### CODE REVIEW

**Comment by ShaneKilkelly** [comment]
This makes docstore compatible with both node 4 and 6, tested on both versions.

**Comment by jpallen** [comment]
Can you do a bit of experimenting to find out what the problem is with `calledWith`? Is it the `ObjectId`? (my guess). It would be great if we could find a pattern that still lets us use `calledWith`, or similar, since this change makes the unit tests more fragile, and less clear.

**Comment by ShaneKilkelly** [comment]
@jpallen will do :)

**Comment by ShaneKilkelly** [comment]
@jpallen yeah, the `sinon.match` api is pretty cool :) we should use it more.

**Pull request merged**
